title = "Xaro"
baseURL = "https://xaro.hecategames.com"
publishDir = "docs"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "./themes/"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-126233226-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/144px.png"
  description = "A space Metroidvania game."
  facebook = ""
  twitter = "https://twitter.com/Damienfamed75"
  instagram = ""
  youtube = ""
  github = "https://www.github.com/Damienfamed75"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/damien-stamates-a3068212a"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/milwaukee.jpg"
  recent_posts_number = 2
